set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR amd64)

set(CMAKE_C_COMPILER x86_64-elf-gcc)
set(CMAKE_CXX_COMPILER x86_64-elf-g++)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(EXTRA_FLAGS "-Wall -Wextra")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${EXTRA_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${EXTRA_FLAGS}")

set(
    COMPILE_OPTIONS_FREESTANDING
    $<$<COMPILE_LANGUAGE:ASM_NASM>: -f elf64>
    $<$<COMPILE_LANGUAGE:C>: -ffreestanding -nostdlib>
)
set(
    COMPILE_OPTIONS_KERNEL
    ${COMPILE_OPTIONS_FREESTANDING}
    $<$<COMPILE_LANGUAGE:C>: -mno-red-zone -mcmodel=kernel>
)

set(
    COMPILE_OPTIONS_USERLAND
    $<$<COMPILE_LANGUAGE:ASM_NASM>: -f elf64>
    $<$<COMPILE_LANGUAGE:C>: -ffreestanding>
)
